// ============================================================
// TROUBLESHOOTING TREE DATA — EN + ZH
// Edit both languages below to match your content
// ============================================================
const treeContent = 
{
  "en": {
    "id": "root",
    "title": "The CT sensor failed to start and report data.",
    "subtitle": "",
    "problem": "",
    "solution": [],
    "children": [
      {
        "id": "root_new_1",
        "title": "The CT device obtains its power supply by utilizing the induced current generated by alternating current. Please ensure that the internal current of the wire being measured is alternating current rather than direct current.",
        "subtitle": "",
        "problem": "",
        "solution": [],
        "children": []
      },
      {
        "id": "root_new_2",
        "title": "Please do not simultaneously pass the neutral wire and the live wire through the coil of the CT sensor; otherwise, the CT device will be unable to obtain the induced current for self-powering.",
        "subtitle": "",
        "problem": "",
        "solution": [],
        "children": []
      },
      {
        "id": "root_new_3",
        "title": "Not any size of alternating current can make the CT device start up. You need to check the minimum starting current of this device in the datasheet of Milesight documentation center(https://www.milesight.com/support/resources/document-center).",
        "subtitle": "",
        "problem": "",
        "solution": [],
        "children": []
      }
    ]
  },
  "zh": {
    "id": "root",
    "title": "CT传感器无法启动并上报数据",
    "subtitle": "",
    "problem": "",
    "solution": [],
    "children": [
      {
        "id": "root_new_1",
        "title": "The CT device obtains its power supply by utilizing the induced current generated by alternating current. Please ensure that the internal current of the wire being measured is alternating current rather than direct current.",
        "subtitle": "",
        "problem": "",
        "solution": [],
        "children": []
      },
      {
        "id": "root_new_2",
        "title": "请不要同时将零线和火线同时穿过CT传感器的线圈，否则CT设备将无法正常获取感应电流以进行自我供电。",
        "subtitle": "",
        "problem": "",
        "solution": [],
        "children": []
      },
      {
        "id": "root_new_3",
        "title": "并不是任意大小的交流电都可以让CT设备启动起来,你需要到Milesight文档中心(https://www.milesight.com/support/resources/document-center)查看该设备的最小启动电流的大小。",
        "subtitle": "",
        "problem": "",
        "solution": [],
        "children": []
      }
    ]
  }
}
;

// ============================================================
// UI TEXT (i18n)
// ============================================================
const uiText = 
{
  "en": {
    "badge": {
      "step": "Step",
      "resolved": "Resolved",
      "escalated": "Escalated"
    },
    "minimap": "Overview",
    "solution": "Solution",
    "buttons": {
      "start": "→ Ready, Start Troubleshooting",
      "resolved": "✓ Issue Resolved",
      "next": "→ Not Resolved, Continue",
      "noMore": "→ Still Unresolved",
      "reset": "↺ Restart",
      "copyPath": "📋 Copy Diagnostic Path",
      "copied": "✓ Copied!"
    },
    "banners": {
      "resolved": {
        "title": "Issue Resolved",
        "subtitle": "— resolved"
      },
      "escalated": {
        "title": "Submit a Ticket",
        "subtitle": "The steps above did not resolve your issue. Please contact Milesight Technical Support.<br>Provide: device model, firmware version, symptom screenshots, and steps already attempted.",
        "linkText": "→ Submit Support Ticket"
      }
    }
  },
  "zh": {
    "badge": {
      "step": "步骤",
      "resolved": "已解决",
      "escalated": "已升级"
    },
    "minimap": "总览",
    "solution": "解决方案",
    "buttons": {
      "start": "→ 准备好了，开始排查",
      "resolved": "✓ 问题已解决",
      "next": "→ 未解决，进入下一步",
      "noMore": "→ 仍无法解决",
      "reset": "↺ 重新开始排查",
      "copyPath": "📋 复制排查路径",
      "copied": "✓ 已复制！"
    },
    "banners": {
      "resolved": {
        "title": "问题已解决",
        "subtitle": "— 故障已排除"
      },
      "escalated": {
        "title": "请提交工单",
        "subtitle": "以上步骤未能解决您的问题，请联系 Milesight 技术支持。<br>请提供：设备型号、固件版本、故障截图、已尝试的排查步骤。",
        "linkText": "→ 提交技术支持工单"
      }
    }
  }
}
;
